### ISSUE TITLE
error with media on android api 30

### ISSUE THREAD

**Issue by denmusic1992** [icerockdev/moko-media#24]
There is an issue working with _MOKO-Media_ and _Permissions_ on android api 30.
When I use this line of code:
```kotlin
viewModelScope.launch {
            try {
                val image: Bitmap = mediaController.pickImage(mediaSource)
                ...
            } catch (error: Exception) {
                ....
            }
```
and click on "only this time" when allowing the app to use Camera permission, I encounter an exception:
`java.lang.IllegalArgumentException: Failed to find configured root that contains /image.png`

But when I call the `pickImage` method again, the permission dialog is not being called and the camera will open.

**Comment by Alex009** [comment]
this may help - https://www.youtube.com/watch?v=YVniFfQ83dU

**Comment by Alex009** [comment]
i test now with "only this time" in sample project - all works fine, without errors
