### ISSUE TITLE
How to pass image to shared module from ios

### ISSUE THREAD

**Issue by Prabhuidsoft** [icerockdev/moko-media#32]
We are need pass uiimage to shared module or need common bytearray for processing image.

**Comment by Alex009** [comment]
in common code available `Bitmap` class - https://github.com/icerockdev/moko-media/blob/master/media/src/commonMain/kotlin/dev/icerock/moko/media/Bitmap.kt
with `toByteArray()` support.

new instance of this class created in platform side
from android bitmap
https://github.com/icerockdev/moko-media/blob/master/media/src/androidMain/kotlin/dev/icerock/moko/media/Bitmap.kt#L10

and from ios uiimage
https://github.com/icerockdev/moko-media/blob/master/media/src/iosMain/kotlin/dev/icerock/moko/media/Bitmap.kt#L13
